services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.0-rc1
    container_name: bunkerweb
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # for QUIC
    environment:
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.0-rc1
    container_name: bw-scheduler
    depends_on:
      - bunkerweb
    volumes:
      - bw-data:/data
    environment:
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: "www.example.com" # replace with your domain
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      AUTO_LETS_ENCRYPT: "yes"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      USE_REVERSE_PROXY: "yes"
      REVERSE_PROXY_URL: "/"
      REVERSE_PROXY_HOST: "http://myredmine:3000"
    restart: "unless-stopped"
    networks:
      - bw-universe

  myredmine:
    image: redmine:5-alpine
    restart: always
    volumes:
      - redmine-data:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: "mydb"
      REDMINE_DB_DATABASE: "redminedb"
      REDMINE_DB_USERNAME: "user"
      REDMINE_DB_PASSWORD: "db-user-pwd" # set a stronger password in a .env file (must match MYSQL_PASSWORD)
    networks:
      - redmine-net
      - bw-services

  mydb:
    image: mysql:8
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "db-root-pwd" # replace with a stronger password
      MYSQL_DATABASE: "redminedb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "db-user-pwd" # replace with a stronger password (must match REDMINE_DB_PASSWORD)
    networks:
      - redmine-net

volumes:
  bw-data:
  redmine-data:
  db-data:


networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  redmine-net:
    name: redmine-net
