apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    bunkerweb.io/AUTO_LETS_ENCRYPT: "yes"
    bunkerweb.io/www.example.com_LIMIT_REQ_URL_1: "/administrator/"
    bunkerweb.io/www.example.com_LIMIT_REQ_RATE_1: "8r/s"
    bunkerweb.io/www.example.com_LIMIT_REQ_URL_2: "/installation/index.php"
    bunkerweb.io/www.example.com_LIMIT_REQ_RATE_2: "8r/s"
spec:
  rules:
    - host: www.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: joomla
                port:
                  number: 80
